name: Go Docker Build Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.5'

    - name: Build Go project
      run: go build -v ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t routenx .

    - name: Run Docker container
      run: |
        docker run -d -p 8080:8080 -p 3000:3000 routenx

    - name: Check Docker container status
      run: |
        docker ps

    - name: Stop Docker container
      run: |
        docker ps -q --filter "ancestor=molidb" | xargs -I {} docker stop {}